# To execute this docker-compose yml file use `docker-compose -f docker-compose.yml up`
# Add the `-d` flag at the end for detached execution

version: "3"
services:

  appium:
    image: appium/appium
    ports:
      - ${APPIUM_PORT}:4723

  selenium-hub:
    image: selenium/hub:3.141.59-20210929
    ports:
      - ${GRID_PORT}:4444
    environment:
      TZ: "Asia/Calcutta"
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 60000
      GRID_TIMEOUT: 60000

  chrome:
    image: selenium/node-chrome:3.141.59-20210929
    volumes:
      - /dev/shm:/dev/shm
      - ./src:/tmp/src/
    depends_on:
      - selenium-hub
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: '2gb'
        reservations:
          cpus: '1'
    environment:
      HUB_HOST: 'selenium-hub'
      HUB_PORT: 4444
      NODE_MAX_SESSION: 5
      NODE_MAX_INSTANCES: 5
      TZ: "Asia/Calcutta"